#!/usr/bin/perl

use warnings;
use strict;

use File::Spec::Functions qw( splitpath );
use App::Slide;

if ( @ARGV != 3 ) {
    my $program = (splitpath( $0 ))[-1];
    die "Usage: $program slidefile.pod slide_dir template_dir\n";
}

my $pod_file = shift;
my $slide_dir = shift;
my $template_dir = shift;

my $set = 
    App::Slide->new(
        pod_file     => $pod_file,
        slide_dir    => $slide_dir,
        template_dir => $template_dir,
    );

my $nslides;
$nslides = $set->generate unless $set->errors;

my @errors = $set->errors;
if ( @errors ) {
    print join( "\n", @errors, "" );
} else {
    print "Generated $nslides slides in $slide_dir\n";
}

exit @errors;
